dokuwiki:
  image: msalcedogomes/docker-dokuwiki
  environment:
  - VIRTUAL_HOST=wiki.supermarches-cooperatifs.fr
  volumes:
  - ./data/www:/var/www
  - ./supervisord.conf:/etc/supervisord.conf
  - ./start.sh:/start.sh
  - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
  - "8000:443"
