dokuwiki:
  image: msalcedogomes/docker-dokuwiki
  environment:
  - VIRTUAL_HOST=wiki.supermarches-cooperatifs.fr
  volumes:
  - ./data/www:/var/www
  - ./supervisord.conf:/etc/supervisord.conf:ro
  - ./start.sh:/start.sh:ro
  - ./nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
  - "80:80"
